server:
  port: 2333
  password: "youshallnotpass"
  sources:
    youtube: true
    bandcamp: true
    soundcloud: true
metrics:
  prometheus: true
logging:
  file:
    path: lavalink.log
    level: info
